### ISSUE TITLE
sudo flutter pub run build_runner build

### ISSUE THREAD

**Issue by pacifire** [lejard-h/chopper#153]
When i run command: `sudo flutter pub run build_runner build`

Error comes as:

```
[SEVERE] chopper_generator:chopper_generator on test/widget_test.dart:

Bad state: Unexpected diagnostics:
/Users/pawanshahani/Documents/flutter/bin/cache/dart-sdk/lib/internal/internal.dart:172:16 - This requires the 'non-nullable' language feature to be enabled.
```

My pubspec.yaml is as follows:

```
name: test_chopper_mobx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: 3.0.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: 3.0.5
  build_runner: 1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

My Chopper class:

```
import 'package:chopper/chopper.dart';

part 'fetchApiData.chopper.dart';

@ChopperApi(baseUrl: '?apikey=cef96cba&t=')
abstract class FetchApiData extends ChopperService {
  @Get(path: '{title}')
  Future<Response> fetchData(@Path('title') String title);
  @Post()
  Future<Response> postData(@Body() Map<String, dynamic> body);

  static FetchApiData create() {
    final client = ChopperClient(
      baseUrl: 'http://www.omdbapi.com/',
      services: [_$FetchApiData()],
      // converter: JsonConverter(),
    );
    return _$FetchApiData(client);
  }
}

```

My Flutter doctor:
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.15.3 19D76, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
