### ISSUE TITLE
Mapping values are not allowed here. Did you miss a colon earlier?

### ISSUE THREAD

**Issue by harshbhavsar011** [lejard-h/chopper#2]
Error on line 17, column 22 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
    chopper_generator: ^0.0.1

```
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.8.0
    chopper_generator: ^0.0.1

  uses-material-design: true
  assets:
    - images/background.png
```
