### ISSUE TITLE
Null error in chopper_generator 4.0.0

### ISSUE THREAD

**Issue by ivoberger** [lejard-h/chopper#257]
Since upgrading `chopper_generator` to 4.0.0 I get this error when running the build with the `--verbose` option:
```
[SEVERE] chopper_generator:chopper_generator:

type 'Null' is not a subtype of type 'String'
package:chopper_generator/chopper_generator.dart 7:58                   chopperGeneratorFactory
```

The erroring code is this:
```dart
library chopper_generator.dart;

import 'package:build/build.dart';
import 'src/generator.dart';

Builder chopperGeneratorFactory(BuilderOptions options) =>
    chopperGeneratorFactoryBuilder(header: options.config['header'] as String);
```

Changing it to this:
```dart
Builder chopperGeneratorFactory(BuilderOptions options) =>
    chopperGeneratorFactoryBuilder(header: options.config['header'] ?? '');
```
fixes the issue. Everything built just fine after that.

**Comment by dramcio** [comment]
+1 - for me the same issue

**Comment by NicoTF** [comment]
i'm getting this problem as well

**Comment by pro100andrey** [comment]
Same

**Comment by djackowski** [comment]
I got the same issue with `4.0.0,` version `chopper_generator: ^4.0.0-nullsafety.1` works for me

**Comment by YoussefRaafatNasry** [comment]
You can create a filed called `build.yaml` in the root of your project as a temporary solution until this gets fixed:

```yaml
# Remove this file when this issue is fixed:
# https://github.com/lejard-h/chopper/issues/257
targets:
  $default:
    builders:
      chopper_generator:
        options:
          header: ''
```
