### ISSUE TITLE
Support latest versions of jsonAnnotation and serializable 

### ISSUE THREAD

**Issue by fryette** [lejard-h/chopper#294]

**Comment by luis901101** [comment]
Hi. I just made a [PR 296](https://github.com/lejard-h/chopper/pull/296) with analyzer dependency upgraded to 2.0.0 which is the required one by json serializable.
In the mean time you can use:
```yaml
chopper_generator: #^4.0.1
    git:
      url: https://github.com/luis901101/chopper.git
      ref: analyzer_upgrade
      path: chopper_generator
```
