### ISSUE TITLE
`Unnecessary use of string interpolation` while the argument is used as the whole path.

### ISSUE THREAD

**Issue by gualse** [lejard-h/chopper#500]
## Steps to Reproduce

1. Create any code like this:
```dart
  @Get(path: '{url}')
  Future<Response<List<Status>>> statusesByUrl(@Path() String url);
```
2. Run `build_runner` and open its result

**Expected results:**

```dart
  @override
  Future<Response<List<Status>>> statusesByUrl(String url) {
    final Uri $url = Uri.parse(url); // or any other way to avoid the warning
    final Request $request = Request(
      'GET',
      $url,
      client.baseUrl,
    );
    return client.send<List<Status>, Status>($request);
  }
```

**Actual results:** 

```dart
  @override
  Future<Response<List<Status>>> statusesByUrl(String url) {
    final Uri $url = Uri.parse('${url}'); // WARNING: Unnecessary use of string interpolation.
    final Request $request = Request(
      'GET',
      $url,
      client.baseUrl,
    );
    return client.send<List<Status>, Status>($request);
  }
```

**Comment by gualse** [comment]
`@Get(path: '{url}#')` fixes the warning but it's a dirty hack

**Comment by techouse** [comment]
Hey,

What happens if you remove the curlies, i.e.

```dart
@Get(path: 'url') // <-- instead of '{url}'
Future<Response<List<Status>>> statusesByUrl(@Path() String url);
```

**Comment by techouse** [comment]
> `@Get(path: '{url}#')` fixes the warning but it's a dirty hack

In general analysis tools should ignore generated files, otherwise, we could add something like

```
// ignore_for_file: unnecessary_brace_in_string_interps
```

**Comment by techouse** [comment]
@gualse 

I have fixed this in #501, however, it will take some time to release this. If you need to use it ASAP you can add this to your `pubspec.yaml`

```yaml
dependency_overrides:
  chopper_generator:
    git:
      url: https://github.com/techouse/chopper.git
      ref: fix/chopper_generator/ignore_unnecessary_string_interpolations
      path: chopper_generator
```
