### ISSUE TITLE
Type 'Response<dynamic>' should be 'Response<User>' to implement expected type 'Response<User>'.

### ISSUE THREAD

**Issue by remalkoil** [lejard-h/chopper#60]
Hello,
i've the following JSON returned by a Post API:
```json
{
  "userId": 1,
  "username": "Daniele",
  "password": null,
  "role": 100,
  "active": true,
  "token": "mytoken",
  "creatorId": null,
  "creationTimeStamp": "2019-06-05T10:11:49"
}
```

I've created the following 'User' model:
```dart
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
part 'user.g.dart';

@JsonSerializable()
class User {
  String username;
  String password;
  String token;
  int userId;
  bool active;
  int role;
  int creatorId;
  String creationTimeStamp; 

  User({this.username, this.password});

  Map<String, dynamic> toJson() => _$UserToJson(this);
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
  factory User.fromJsonString(String json) => _$UserFromJson(jsonDecode(json));
}
```

Also, I've created the following ApiService:
```dart
import 'dart:async';
import 'package:chopper/chopper.dart';
import 'package:domoweb/src/models/user.dart';
part 'api_service.chopper.dart';

@ChopperApi(baseUrl: '')
abstract class ApiService extends ChopperService {
  static ApiService create([ChopperClient client]) => _$ApiService(client);
  
  @Post(path: '/api/Auth/login')
  Future<Response<User>> login(@Body() User user);
}


```

When i call the login method it's not working.
```dart
Response<User> resp = await _api.login(User(username: 'myusername', password: 'mypassword'));
```
The error response message is: **Type 'Response<dynamic>' should be 'Response<User>' to implement expected type 'Response<User>'.**

The content of pubspec.yaml is:
```yaml
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.11.0
  chopper: ^2.3.0
  json_annotation:

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  chopper_generator: ^2.2.0
  analyzer:
  json_serializable:
```

I've already searched on other opened/closed issues but i've not solved my problem.
Can someone help me?
